name: EdgeLink
options:
  deploymentTarget:
    macOS: "13.0"
targets:
  EdgeLinkKit:
    type: framework
    platform: macOS
    sources:
      - Sources/EdgeLinkKit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  EdgeLinkMac:
    type: application
    platform: macOS
    bundleId: com.edgelink.mac
    sources:
      - Sources/App
    dependencies:
      - target: EdgeLinkKit
      - sdk: libsqlite3.tbd
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: MW4GWYGX56
        PRODUCT_BUNDLE_IDENTIFIER: com.edgelink.mac
    info:
      path: Sources/App/Info.plist
      properties:
        CFBundleDisplayName: EdgeLink
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright 2026 EdgeLink contributors"
  EdgeLinkKitTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/EdgeLinkKitTests
    dependencies:
      - target: EdgeLinkKit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
schemes:
  EdgeLinkKit:
    build:
      targets:
        EdgeLinkKit: all
    test:
      targets:
        - EdgeLinkKitTests
  EdgeLinkMac:
    build:
      targets:
        EdgeLinkMac: all
